
---
- name: install sonarqube on Centos
  hosts: jenkins
  become: true
  tasks:
  - name: create
    group:
      name: sonar
  - name: create user sonar to manage the sonar service
    user:
      name: sonar
      group: sonar
      createhome: no
      shell: /bin/false
      state: present
  - name: download sonarqube
    get_url:
      url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.5.zip
      dest: /tmp/sonarqube-7.5.zip
    retries: 5
    delay: 10
  - name: decompress sonarqube archive
    unarchive:
      src: /tmp/sonarqube-7.5.zip
      dest: /opt/
      owner: sonar
      group: sonar
      copy: no
  - name: remove sonar archive
    file:
      path: /tmp/sonarqube-7.5.zip
      state: absent
  - name: create systemd service for sonar
    template:
      src: sonar.service.j2
      dest: /etc/systemd/system/sonar.service
      owner: root
      group: root
      mode: 0755
  - name: reload systemd daemon
    systemd:
      daemon_reload: yes
  - name: start sonar service
    service:
      name: sonar
      state: started
      enabled: yes
